#!/usr/bin/env python

import rospy

from std_msgs.msg import Float64, Float64MultiArray


class PincherGroupPositionController:

    JOINTS = ["arm_shoulder_pan_joint",
              "arm_shoulder_lift_joint",
              "arm_elbow_flex_joint",
              "arm_wrist_flex_joint"]

    def __init__(self):
        self.command_pubs = []
        for joint in self.JOINTS:
            pub = rospy.Publisher(joint + '/command', Float64, queue_size=5)
            self.command_pubs.append(pub)

        self.command_sub = rospy.Subscriber(
            '~command', Float64MultiArray, self.commandCb, queue_size=5)

    def commandCb(self, cmd):
        for pub, angle in zip(self.command_pubs, cmd.data):
            pub.publish(Float64(angle))

if __name__ == '__main__':
    rospy.init_node('pincher_group_position_controller')
    controller = PincherGroupPositionController()
    rospy.spin()
