read_rate: 15
write_rate: 25

joints:
  arm_shoulder_pan_joint:
    id: 1
    type: dynamixel
    neutral: 512
    min_angle: -150
    max_angle: 150
    max_speed: 90
  arm_shoulder_lift_joint:
    id: 2
    type: dynamixel
    min_angle: -120
    max_angle: 120
    max_speed: 90
  arm_elbow_flex_joint:
    id: 3
    type: dynamixel
    min_angle: -139
    max_angle: 139
    max_speed: 90
  arm_wrist_flex_joint:
    id: 4
    type: dynamixel
    min_angle: -98
    max_angle: 103
    max_speed: 90
  gripper_joint:
    id: 5
    type: dynamixel
    min_angle: -149
    max_angle: 0
    max_speed: 90

controllers:
  arm_controller: 
    type: follow_controller
    joints:
      - arm_shoulder_pan_joint
      - arm_shoulder_lift_joint
      - arm_elbow_flex_joint
      - arm_wrist_flex_joint
    action_name: arm_controller/follow_joint_trajectory
    onboard: False
