<?xml version="1.0"?>
<!-- PhantomX Pincher arm description 
BSD 3-Clause License

Copyright (c) 2021, Willow Garage, Inc.
Copyright (c) 2021, Kell Ideas Ltd.
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

    * Redistributions of source code must retain the above copyright
      notice, this list of conditions and the following disclaimer.
    * Redistributions in binary form must reproduce the above copyright
      notice, this list of conditions and the following disclaimer in the
      documentation and/or other materials provided with the distribution.
    * Neither the name of the Willow Garage, Inc. nor the names of its
      contributors may be used to endorse or promote products derived from
      this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE
LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
POSSIBILITY OF SUCH DAMAGE.
-->

<robot xmlns:xacro="http://ros.org/wiki/xacro">
  <xacro:include filename="$(find pincher_arm_description)/urdf/arm_hardware.xacro"/>

  <material name="White">
    <color rgba="0.87 0.90 0.87 1.0"/>
  </material>
  <material name="Black">
    <color rgba="0.08 0.08 0.08 1.0"/>
  </material>
  <material name="Gray">
    <color rgba="0.2 0.2 0.21 1.0"/>
  </material>
  <material name="Green">
    <color rgba="0.22 0.32 0.14 1.0"/>
  </material>

  <xacro:macro name="pincher_arm" params="
      color:=Gray
      joints_vlimit:=1.571
      pan_llimit:=-2.617
      pan_ulimit:=2.617
      shoulder_llimit:=-2.09
      shoulder_ulimit:=2.09
      elbow_llimit:=-2.42
      elbow_ulimit:=2.42
      wrist_llimit:=-1.71
      wrist_ulimit:=1.79
      gripper_llimit:=-2.6
      gripper_ulimit:=0.0">

    <link name="arm_base_link"/>

    <!-- shoulder pan joint -->
    <xacro:dynamixel_AX12_fixed parent="arm_base_link" name="arm_shoulder_pan_servo">
      <origin xyz="0 0 0" rpy="${pi/2} 0 ${pi/2}"/>
    </xacro:dynamixel_AX12_fixed>

    <xacro:bioloid_F3_revolute parent="arm_shoulder_pan_servo_link" name="arm_shoulder_pan" color="${color}"
                               vlimit="${joints_vlimit}" llimit="${pan_llimit}" ulimit="${pan_ulimit}">
      <origin xyz="0 ${AX12_WIDTH/2} 0" rpy="${-pi/2} ${pi/2} ${pi}"/>
    </xacro:bioloid_F3_revolute>

    <!-- shoulder lift joint -->
    <xacro:dynamixel_AX12_fixed parent="arm_shoulder_pan_link" name="arm_shoulder_lift_servo">
      <origin xyz="0 0 ${-AX12_HEIGHT-F10_HEIGHT+0.001}" rpy="0 ${pi} 0"/>
    </xacro:dynamixel_AX12_fixed>

    <xacro:bioloid_F4_revolute parent="arm_shoulder_lift_servo_link" name="arm_shoulder_lift" color="${color}"
                               vlimit="${joints_vlimit}" llimit="${shoulder_llimit}" ulimit="${shoulder_ulimit}">
      <origin xyz="0 0 0" rpy="0 0 0"/>
    </xacro:bioloid_F4_revolute>

    <xacro:bioloid_F10_fixed parent="arm_shoulder_lift_link" name="arm_shoulder_F10_0" color="${color}">
      <origin xyz="0 0 ${F4_HEIGHT+F10_HEIGHT/2}" rpy="0 0 0"/>
    </xacro:bioloid_F10_fixed>

    <xacro:bioloid_F10_fixed parent="arm_shoulder_F10_0_link" name="arm_shoulder_F10_1" color="${color}">
      <origin xyz="0 0 ${F10_HEIGHT}" rpy="0 0 0"/>
    </xacro:bioloid_F10_fixed>

    <xacro:bioloid_F10_fixed parent="arm_shoulder_F10_1_link" name="arm_shoulder_F10_2" color="${color}">
      <origin xyz="0 0 ${F10_HEIGHT}" rpy="0 0 0"/>
    </xacro:bioloid_F10_fixed>

    <xacro:bioloid_F3_fixed parent="arm_shoulder_F10_2_link" name="arm_shoulder_F3_0" color="${color}">
      <origin xyz="0 0 ${F10_HEIGHT/2}" rpy="0 ${pi} 0"/>
    </xacro:bioloid_F3_fixed>

    <!-- elbow joint -->
    <xacro:dynamixel_AX12_fixed parent="arm_shoulder_F3_0_link" name="arm_elbow_flex_servo">
      <origin xyz="0 0 ${-AX12_HEIGHT-F10_HEIGHT+0.001}" rpy="0 ${pi} 0"/>
    </xacro:dynamixel_AX12_fixed>

    <xacro:bioloid_F4_revolute parent="arm_elbow_flex_servo_link" name="arm_elbow_flex" color="${color}"
                               vlimit="${joints_vlimit}" llimit="${elbow_llimit}" ulimit="${elbow_ulimit}">
      <origin xyz="0 0 0" rpy="0 0 0"/>
    </xacro:bioloid_F4_revolute>

    <xacro:bioloid_F10_fixed parent="arm_elbow_flex_link" name="arm_elbow_F10_0" color="${color}">
      <origin xyz="0 0 ${F4_HEIGHT+F10_HEIGHT/2}" rpy="0 0 0"/>
    </xacro:bioloid_F10_fixed>

    <xacro:bioloid_F10_fixed parent="arm_elbow_F10_0_link" name="arm_elbow_F10_1" color="${color}">
      <origin xyz="0 0 ${F10_HEIGHT}" rpy="0 0 0"/>
    </xacro:bioloid_F10_fixed>

    <xacro:bioloid_F10_fixed parent="arm_elbow_F10_1_link" name="arm_elbow_F10_2" color="${color}">
      <origin xyz="0 0 ${F10_HEIGHT}" rpy="0 0 0"/>
    </xacro:bioloid_F10_fixed>

    <xacro:bioloid_F3_fixed parent="arm_elbow_F10_2_link" name="arm_elbow_F3_0" color="${color}">
      <origin xyz="0 0 ${F10_HEIGHT/2}" rpy="0 ${pi} 0"/>
    </xacro:bioloid_F3_fixed>

    <!-- wrist joint -->
    <xacro:dynamixel_AX12_fixed parent="arm_elbow_F3_0_link" name="arm_wrist_flex_servo">
      <origin xyz="0 0 ${-AX12_HEIGHT-F10_HEIGHT+0.001}" rpy="0 ${pi} 0"/>
    </xacro:dynamixel_AX12_fixed>

    <xacro:bioloid_F2_revolute parent="arm_wrist_flex_servo_link" name="arm_wrist_flex" color="${color}"
                               vlimit="${joints_vlimit}" llimit="${wrist_llimit}" ulimit="${wrist_ulimit}">
      <origin xyz="0 0 0" rpy="0 0 0"/>
    </xacro:bioloid_F2_revolute>

    <xacro:bioloid_F3_fixed parent="arm_wrist_flex_link" name="arm_wrist_F3_0" color="${color}">
      <origin xyz="0 0 ${F2_HEIGHT}" rpy="0 ${pi} ${-pi}"/>
    </xacro:bioloid_F3_fixed>
    
    <!-- gripper joint -->
    <xacro:dynamixel_AX12_fixed parent="arm_wrist_F3_0_link" name="gripper_servo" >
      <origin xyz="0 0 ${-AX12_WIDTH/2}" rpy="${pi/2} ${pi} ${pi/2}"/>
    </xacro:dynamixel_AX12_fixed>
    
    <xacro:gripper_finger_base parent="gripper_servo_link" name="gripper_finger_base" color="${color}">
      <origin xyz="0  ${AX12_WIDTH/2} 0" rpy="${pi} 0 ${pi/2}"/>
    </xacro:gripper_finger_base>

    <link name="gripper_active_link"/>
    <joint name="gripper_joint" type="revolute">
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <axis xyz="1 0 0"/>
      <limit effort="30" velocity="${joints_vlimit}" lower="${gripper_llimit}" upper="${gripper_ulimit}"/>
      <parent link="gripper_finger_base_link"/>
      <child link="gripper_active_link"/>
    </joint>

    <!-- Finger 1 --> 
    <xacro:pincher_finger name="gripper_finger1" color="${color}" >
      <origin xyz="0 0.0115 0" rpy="${pi/2} 0 ${pi/2}"/>
    </xacro:pincher_finger>

    <joint name="gripper_finger1_joint" type="prismatic">
      <origin xyz="0.019 0 0" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
      <limit effort="30" velocity="0.01" lower="0.001" upper="0.0158"/>
      <parent link="gripper_finger_base_link"/>
      <child link="gripper_finger1_link"/>
    </joint> 
      
    <!-- Finger 2 -->
    <xacro:pincher_finger name="gripper_finger2" color="${color}" >
      <origin xyz="0 0.0115 0" rpy="${pi/2} 0 ${pi/2}"/>
    </xacro:pincher_finger>

    <joint name="gripper_finger2_joint" type="prismatic">
      <origin xyz="0.019 0 0" rpy="${pi} 0 0"/>
      <axis xyz="0 1 0"/>
      <limit effort="30" velocity="0.01" lower="0.001" upper="0.0158"/>
      <parent link="gripper_finger_base_link"/>
      <child link="gripper_finger2_link"/>
      <!-- <mimic joint="gripper_finger1_joint"/> -->
    </joint>

    <!-- fake gripper joint -->
    <link name="gripper_fake_link"/>
    <joint name="gripper_fake_joint" type="revolute">
      <origin xyz="0.02 0 0" rpy="0 0 0"/>
      <parent link="gripper_finger_base_link"/>
      <child link="gripper_fake_link"/>
      <limit effort="30" velocity="1" lower="-3.14" upper="3.14"/>
      <axis xyz="1 0 0"/>
    </joint>

  </xacro:macro>

</robot>
